import asyncio
import numpy as np
from av import VideoFrame
from aiortc import VideoStreamTrack

from PIL import Image
import math

class SFUVideoTrack(VideoStreamTrack):
    """
    A Video track generated by the Host MCU and sent to clients.
    It yields a composited Grid Canvas of all active video streams.
    """
    def __init__(self, sfu_manager):
        super().__init__()
        self.sfu = sfu_manager
        
    async def recv(self):
        pts, time_base = await self.next_timestamp()
        
        # Pull the composited canvas
        canvas_arr = self.sfu.get_composited_canvas()
        
        frame = VideoFrame.from_ndarray(canvas_arr, format="bgr24")
        frame.pts = pts
        frame.time_base = time_base
        
        # Enforce exactly 15 FPS
        await asyncio.sleep(1.0 / 15.0)
        return frame

class SFUVideoManager:
    """
    Central Video MCU (Multipoint Control Unit) for the Host.
    Composites multiple incoming video streams into a single Grid Canvas.
    """
    def __init__(self, loop):
        self.loop = loop
        self.incoming_tracks = {} # {peer_id: track}
        self.latest_frames = {} # {peer_id: ndarray}
        self.consume_tasks = {}
        
        self.canvas_width = 1280
        self.canvas_height = 720
        self.black_canvas = np.zeros((self.canvas_height, self.canvas_width, 3), dtype=np.uint8)
        
    def add_track(self, peer_id, track):
        self.incoming_tracks[peer_id] = track
        self.consume_tasks[peer_id] = self.loop.create_task(self._consume(peer_id, track))
            
    def remove_track(self, peer_id):
        if peer_id in self.incoming_tracks:
            del self.incoming_tracks[peer_id]
        if peer_id in self.consume_tasks:
            self.consume_tasks[peer_id].cancel()
            del self.consume_tasks[peer_id]
        if peer_id in self.latest_frames:
            del self.latest_frames[peer_id]
            
    def set_active_speaker(self, peer_id):
        # We no longer switch active speaker exclusively, 
        # but we could use this to highlight the speaker's border in the grid.
        pass
            
    def feed_local_frame(self, frame_arr):
        self.latest_frames["local"] = frame_arr
            
    async def _consume(self, peer_id, track):
        try:
            while True:
                frame = await track.recv()
                self.latest_frames[peer_id] = frame.to_ndarray(format="bgr24")
        except Exception as e:
            print(f"[MCU] Video consumer err for {peer_id}: {e}")
            
    def get_composited_canvas(self):
        # 1. Gather active frames
        active_frames = {k: v for k, v in self.latest_frames.items() if v is not None}
        n = len(active_frames)
        
        if n == 0:
            return self.black_canvas.copy()
            
        canvas = np.zeros((self.canvas_height, self.canvas_width, 3), dtype=np.uint8)
        
        # 2. Determine Grid Layout (1x1, 2x2, 3x3)
        cols = math.ceil(math.sqrt(n))
        rows = math.ceil(n / cols)
        
        cell_w = self.canvas_width // cols
        cell_h = self.canvas_height // rows
        
        # 3. Paste frames into cells
        idx = 0
        for peer_id, arr in active_frames.items():
            r = idx // cols
            c = idx % cols
            
            # Use PIL to resize the frame to fit the cell
            try:
                img = Image.fromarray(arr, "BGR")
                img.thumbnail((cell_w, cell_h), Image.Resampling.LANCZOS)
                resized_arr = np.array(img)
                
                h, w, _ = resized_arr.shape
                
                # Center the image in the cell
                y_offset = r * cell_h + (cell_h - h) // 2
                x_offset = c * cell_w + (cell_w - w) // 2
                
                canvas[y_offset:y_offset+h, x_offset:x_offset+w] = resized_arr
            except Exception as e:
                pass
                
            idx += 1
            
        return canvas
        
    def create_client_track(self):
        return SFUVideoTrack(self)
